amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.2
    alpha4: 0.2
    min_particles: 500
    max_particles: 3000
    update_min_d: 0.1
    update_min_a: 0.15

bt_navigator:
  ros__parameters:
    use_sim_time: true
    bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/follow_point.xml"

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.05
      allow_unknown: true
      use_astar: false

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      holonomic: true
      
      desired_linear_vel: 0.15
      max_linear_vel: 0.2
      lookahead_dist: 0.3
      min_lookahead_dist: 0.15
      rotate_to_heading_angular_vel: 0.2
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.1
      use_regulated_linear_velocity_scaling: true
      use_approach_linear_velocity_scaling: true
      min_approach_linear_velocity: 0.05
    
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.1
      stateful: true